import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_analytics/firebase_analytics.dart';

import '../../core/services/firestore_service.dart';
import '../../core/utils/result.dart';
import '../models/notification_model.dart';
import '../models/request_model.dart';
import '../models/ride_model.dart';
import '../repositories/notification_repository.dart';

/// Repository responsible for all Ride Request database operations.
class RideRequestRepository {
  final FirestoreService _firestoreService;
  final NotificationRepository _notificationRepo;
  final FirebaseAnalytics _analytics = FirebaseAnalytics.instance;

  RideRequestRepository({
    FirestoreService? firestoreService,
    NotificationRepository? notificationRepo,
  })  : _firestoreService = firestoreService ?? FirestoreService(),
        _notificationRepo = notificationRepo ?? NotificationRepository();

  /// Submits a new ride request to Firestore.
  /// The document ID is generated by Firestore and written into the model.
  Future<Result<String>> submitRequest(RideRequestModel request) async {
    try {
      final docRef = _firestoreService.rideRequestsCollection.doc();
      final withId = request.copyWith(requestId: docRef.id);
      await docRef.set(withId.toMap());

      unawaited(_analytics.logEvent(
        name: 'ride_joined',
        parameters: {'rideId': request.rideId, 'passengerId': request.requesterUid},
      ));

      // Notify the ride owner about the new request.
      unawaited(_notificationRepo.createNotification(NotificationModel(
        id: '',
        userId: request.ownerUid,
        title: 'New Ride Request',
        body: 'Someone has requested to join your ride.',
        type: 'new_request',
        isRead: false,
        createdAt: DateTime.now(),
        relatedId: docRef.id,
      )));

      return Success(docRef.id);
    } on FirebaseException catch (e) {
      return Failure(e.message ?? 'Failed to submit request.', FirestoreException(e.code));
    } catch (e) {
      return Failure('An unexpected error occurred.', Exception(e.toString()));
    }
  }

  /// Checks whether [requesterUid] has already sent a non-cancelled request
  /// for [rideId]. Returns the existing model if found, null otherwise.
  Future<Result<RideRequestModel?>> getExistingRequest({
    required String rideId,
    required String requesterUid,
  }) async {
    try {
      final snapshot = await _firestoreService.rideRequestsCollection
          .where('rideId', isEqualTo: rideId)
          .where('requesterUid', isEqualTo: requesterUid)
          .where('status', whereIn: ['pending', 'accepted'])
          .limit(1)
          .get();

      if (snapshot.docs.isEmpty) return const Success(null);
      return Success(RideRequestModel.fromDocument(snapshot.docs.first));
    } on FirebaseException catch (e) {
      return Failure(e.message ?? 'Failed to check existing request.', FirestoreException(e.code));
    } catch (e) {
      return Failure('An unexpected error occurred.', Exception(e.toString()));
    }
  }

  /// Fetches a fresh copy of a [RideModel] for validation before submission.
  Future<Result<RideModel>> getRide(String rideId) async {
    try {
      final doc = await _firestoreService.ridesCollection.doc(rideId).get();
      if (!doc.exists) {
        return const Failure('Ride not found.', FirestoreException('Ride document does not exist.'));
      }
      final data = doc.data() as Map<String, dynamic>;
      return Success(RideModel.fromMap(data, doc.id));
    } on FirebaseException catch (e) {
      return Failure(e.message ?? 'Failed to fetch ride.', FirestoreException(e.code));
    } catch (e) {
      return Failure('An unexpected error occurred.', Exception(e.toString()));
    }
  }

  /// Fetches all requests for rides owned by [ownerUid].
  Stream<List<RideRequestModel>> streamRequestsForOwner(String ownerUid) {
    return _firestoreService.rideRequestsCollection
        .where('ownerUid', isEqualTo: ownerUid)
        .snapshots()
        .map((snapshot) {
          final list = snapshot.docs
              .map((doc) => RideRequestModel.fromDocument(doc))
              .toList();
          list.sort((a, b) => b.requestedAt.compareTo(a.requestedAt));
          return list;
        });
  }

  /// Transactionally accepts a request.
  /// 1. Reads the Ride document to verify seats are available.
  /// 2. Decreases the Ride's availableSeats.
  /// 3. Updates the Request's status to accepted.
  Future<Result<void>> acceptRequest(RideRequestModel request) async {
    try {
      final rideRef = _firestoreService.ridesCollection.doc(request.rideId);
      final reqRef = _firestoreService.rideRequestsCollection.doc(request.requestId);

      await FirebaseFirestore.instance.runTransaction((transaction) async {
        final rideDoc = await transaction.get(rideRef);
        final reqDoc = await transaction.get(reqRef);

        if (!rideDoc.exists || !reqDoc.exists) {
          throw const FirestoreException('Ride or Request document does not exist.');
        }

        final currentSeats = (rideDoc.data() as Map<String, dynamic>)['availableSeats'] as int? ?? 0;
        final currentReqStatus = (reqDoc.data() as Map<String, dynamic>)['status'] as String? ?? 'pending';

        if (currentReqStatus != RideRequestStatus.pending.name) {
          throw const FirestoreException('Request is no longer pending.');
        }

        if (currentSeats < request.requestedSeats) {
          throw const FirestoreException('Not enough seats available.');
        }

        final newSeats = currentSeats - request.requestedSeats;

        // Update ride seats (and status if needed, though typically we just leave it active until seats == 0? 
        // For now just decrement seats).
        transaction.update(rideRef, {
          'availableSeats': newSeats,
        });

        // Accept request
        transaction.update(reqRef, {
          'status': RideRequestStatus.accepted.name,
        });
      });

      // Notify the passenger that their request was accepted.
      unawaited(_notificationRepo.createNotification(NotificationModel(
        id: '',
        userId: request.requesterUid,
        title: 'Ride Request Accepted! 🎉',
        body: 'Your ride request has been accepted. Contact details are now available.',
        type: 'accepted',
        isRead: false,
        createdAt: DateTime.now(),
        relatedId: request.requestId,
      )));

      return const Success(null);
    } on FirestoreException catch (e) {
      return Failure(e.message, e);
    } on FirebaseException catch (e) {
      return Failure(e.message ?? 'Failed to accept request.', FirestoreException(e.code));
    } catch (e) {
      return Failure('An unexpected error occurred.', Exception(e.toString()));
    }
  }

  /// Rejects a ride request.
  Future<Result<void>> rejectRequest(String requestId, {required String requesterUid}) async {
    try {
      await _firestoreService.rideRequestsCollection.doc(requestId).update({
        'status': RideRequestStatus.rejected.name,
      });

      // Notify the passenger that their request was rejected.
      unawaited(_notificationRepo.createNotification(NotificationModel(
        id: '',
        userId: requesterUid,
        title: 'Ride Request Declined',
        body: 'Your ride request was not accepted. Try looking for another ride.',
        type: 'rejected',
        isRead: false,
        createdAt: DateTime.now(),
        relatedId: requestId,
      )));

      return const Success(null);
    } on FirebaseException catch (e) {
      return Failure(e.message ?? 'Failed to reject request.', FirestoreException(e.code));
    } catch (e) {
      return Failure('An unexpected error occurred.', Exception(e.toString()));
    }
  }

  /// Cancels a ride request (by the passenger).
  /// If the request was already accepted, restores the available seats on the ride.
  Future<Result<void>> cancelRequest(RideRequestModel request) async {
    try {
      final reqRef = _firestoreService.rideRequestsCollection.doc(request.requestId);

      if (request.status == RideRequestStatus.accepted) {
        final rideRef = _firestoreService.ridesCollection.doc(request.rideId);

        await FirebaseFirestore.instance.runTransaction((transaction) async {
          final rideDoc = await transaction.get(rideRef);
          final reqDoc = await transaction.get(reqRef);

          if (!rideDoc.exists || !reqDoc.exists) {
            throw const FirestoreException('Ride or Request document does not exist.');
          }

          final currentReqStatus = (reqDoc.data() as Map<String, dynamic>)['status'] as String? ?? 'pending';

          if (currentReqStatus != RideRequestStatus.accepted.name) {
            throw const FirestoreException('Request status changed. Cannot cancel as accepted.');
          }

          final currentSeats = (rideDoc.data() as Map<String, dynamic>)['availableSeats'] as int? ?? 0;
          final newSeats = currentSeats + request.requestedSeats;

          // Restore seats
          transaction.update(rideRef, {
            'availableSeats': newSeats,
          });

          // Cancel request
          transaction.update(reqRef, {
            'status': RideRequestStatus.cancelled.name,
          });
        });
      } else {
        // Just cancel the request without touching seats
        await reqRef.update({
          'status': RideRequestStatus.cancelled.name,
        });
      }

      return const Success(null);
    } on FirestoreException catch (e) {
      return Failure(e.message, e);
    } on FirebaseException catch (e) {
      return Failure(e.message ?? 'Failed to cancel request.', FirestoreException(e.code));
    } catch (e) {
      return Failure('An unexpected error occurred.', Exception(e.toString()));
    }
  }

  /// Fetches all requests made by [requesterUid].
  Stream<List<RideRequestModel>> streamRequestsByPassenger(String requesterUid) {
    return _firestoreService.rideRequestsCollection
        .where('requesterUid', isEqualTo: requesterUid)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => RideRequestModel.fromMap(doc.data() as Map<String, dynamic>, doc.id))
            .toList());
  }

  Future<List<RideRequestModel>> getRequestsByPassenger(String requesterUid) async {
    final snapshot = await _firestoreService.rideRequestsCollection
        .where('requesterUid', isEqualTo: requesterUid)
        .get();
    return snapshot.docs
        .map((doc) => RideRequestModel.fromMap(doc.data() as Map<String, dynamic>, doc.id))
        .toList();
  }
}
