// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnM88EidG3BSnFWL1wpxgbfNSqkStCoXU',
    appId: '1:669295324518:web:4472a39d44473170e1aca7',
    messagingSenderId: '669295324518',
    projectId: 'autoshare-df55f',
    authDomain: 'autoshare-df55f.firebaseapp.com',
    storageBucket: 'autoshare-df55f.firebasestorage.app',
    measurementId: 'G-TDNEQRXJDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEJaQlWGW0fM8n28WUAC6_0fMTWPIPnY',
    appId: '1:669295324518:android:03a48946a480a0e3e1aca7',
    messagingSenderId: '669295324518',
    projectId: 'autoshare-df55f',
    storageBucket: 'autoshare-df55f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0RZ0OKjYFlPhMB_DjDk-3JING33qbvw',
    appId: '1:669295324518:ios:4f0bd8bfb8c7acfce1aca7',
    messagingSenderId: '669295324518',
    projectId: 'autoshare-df55f',
    storageBucket: 'autoshare-df55f.firebasestorage.app',
    iosBundleId: 'com.autoshare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0RZ0OKjYFlPhMB_DjDk-3JING33qbvw',
    appId: '1:669295324518:ios:4f0bd8bfb8c7acfce1aca7',
    messagingSenderId: '669295324518',
    projectId: 'autoshare-df55f',
    storageBucket: 'autoshare-df55f.firebasestorage.app',
    iosBundleId: 'com.autoshare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnM88EidG3BSnFWL1wpxgbfNSqkStCoXU',
    appId: '1:669295324518:web:03ab60536bd84e5fe1aca7',
    messagingSenderId: '669295324518',
    projectId: 'autoshare-df55f',
    authDomain: 'autoshare-df55f.firebaseapp.com',
    storageBucket: 'autoshare-df55f.firebasestorage.app',
    measurementId: 'G-80SC7HCTGS',
  );
}
